apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: vqvg2s4ii-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/vqvg2s4ii-dotnet-basic-gitops